name: use action workflow

on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependency
        run: npm install

      - name: Run tests
        run: npm test

  deploy-app:
    runs-on: ubuntu-latest
    needs: test  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependency
        run: npm install

      - name: Start server
        run: node server.js